%% read
filterExt = '*.3mf';
if exist("filepath")
    filter = [filepath filterExt];
else
    filter = filterExt;
end
[file,filepath] = uigetfile(filter);
[~,fname,ext] = fileparts(file);
% [filepath,fname,ext] = fileparts(...
%     "C:\Users\Dimitrii Nikolaev\nextcloud - Home\_Dissertation\CAD\Lasertracker Leica\exportiert\1.5 INCH SMR.3MF"...
%     );

[V,F,CData] = read3MF(sprintf("%s/%s%s",filepath,fname,ext));

%% plot
figure
p=patch( ...
    'Vertices',         V, ...
    'Faces',            F,...
    'FaceColor',        'flat',...
    'EdgeColor',        'none',...
    'CData',            CData, ...
    'FaceVertexCData',  CData, ...
    'CDataMapping',     'direct' ...
 );
axis equal;light
view([-140 44])
xlabel('X');ylabel('Y');zlabel('Z');
hold on
plot3([0 50],[0 0],[0 0],'r');
plot3([0 0],[0 50],[0 0],'g');
plot3([0 0],[0 0],[0 50],'b');

%% write stl
stlwrite_(...
    sprintf("./%s.stl",fname),...
    F,V,...
    'FaceColor',CData*31 ...
);